# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [46]:
import pandas as pd
import numpy as np 

from sklearn.datasets import load_boston
from sklearn.datasets import load_iris

from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold, cross_val_score

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, accuracy_score, balanced_accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report

from sklearn.linear_model import LinearRegression , LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import LinearSVC, SVC
from sklearn.neural_network import MLPClassifier

## Regression Model Evaluation

Load the boston dataset using sklearn and get the datasets X and y containing the target and the rest of the variables

In [47]:
boston = load_boston()
X = boston.data
y = boston.target

### Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [48]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

### Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [49]:
rg = LinearRegression()
rg.fit(X_train, y_train)
y_train_pred = rg.predict(X_train)
y_test_pred = rg.predict(X_test)

### Calculate and print R-squared for both the training and the testing set.

In [50]:
print("r2_score training:",r2_score(y_train, y_train_pred))
print("r2_score testing:",r2_score(y_test, y_test_pred))

r2_score training: 0.7508856358979673
r2_score testing: 0.6687594935356329


### Calculate and print mean squared error for both the training and the testing set.

In [51]:
print("mean_squared_error training:",mean_squared_error(y_train, y_train_pred))
print("mean_squared_error testing:",mean_squared_error(y_test, y_test_pred))

mean_squared_error training: 21.641412753226312
mean_squared_error testing: 24.291119474973456


### Calculate and print mean absolute error for both the training and the testing set.

In [52]:
print("mean_absolute_error training:",mean_absolute_error(y_train, y_train_pred))
print("mean_absolute_error testing:",mean_absolute_error(y_test, y_test_pred))

mean_absolute_error training: 3.3147716267832226
mean_absolute_error testing: 3.1890919658878287


## Classification Model Evaluation

Load the iris dataset using sklearn and get the datasets X and y containing the target and the rest of the variables

In [53]:
iris = load_iris()
X = iris.data
y = iris.target

### Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [54]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

### Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [55]:
logit = LogisticRegression()
logit.fit(X_train, y_train)
y_train_pred = logit.predict(X_train)
y_test_pred = logit.predict(X_test)

C:\Users\Miguel\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


### Calculate and print the accuracy score for both the training and the testing set.

In [56]:
print("accuracy_score training:",accuracy_score(y_train, y_train_pred))
print("accuracy_score testing:",accuracy_score(y_test, y_test_pred))

accuracy_score training: 0.975
accuracy_score testing: 1.0


### Calculate and print the balanced accuracy score for both the training and the testing set.

In [57]:
print("balanced_accuracy_score training:",balanced_accuracy_score(y_train, y_train_pred))
print("balanced_accuracy_score testing:",balanced_accuracy_score(y_test, y_test_pred))

balanced_accuracy_score training: 0.975609756097561
balanced_accuracy_score testing: 1.0


### Calculate and print the precision score for both the training and the testing set.

In [58]:
print("precision_score training:",precision_score(y_train, y_train_pred, average = "weighted"))
print("precision_score testing:",precision_score(y_test, y_test_pred, average = "weighted"))

precision_score training: 0.9767857142857144
precision_score testing: 1.0


### Calculate and print the recall score for both the training and the testing set.

In [59]:
print("recall_score training:",recall_score(y_train, y_train_pred, average = "weighted"))
print("recall_score testing:",recall_score(y_test, y_test_pred, average = "weighted"))

recall_score training: 0.975
recall_score testing: 1.0


### Calculate and print the F1 score for both the training and the testing set.

In [60]:
print("f1_score training:",f1_score(y_train, y_train_pred, average = "weighted"))
print("f1_score testing:",f1_score(y_test, y_test_pred, average = "weighted"))

f1_score training: 0.9749882794186592
f1_score testing: 1.0


### Generate confusion matrices for both the training and the testing set.

In [61]:
print(confusion_matrix( y_train_pred, y_train))

[[40  0  0]
 [ 0 38  0]
 [ 0  3 39]]


In [62]:
print(confusion_matrix( y_test_pred, y_test))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

#### Boston

In [94]:
X = boston.data
y = boston.target

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [96]:
import sklearn
sorted(sklearn.metrics.SCORERS.keys())

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'roc_auc_ovo',
 'roc_auc_ovo_weighted',
 'roc_auc_ovr',
 'roc_auc_ovr_weighted',
 'v_measure_score']

In [97]:
def baseline_report(model, X_train, X_test, y_train, y_test, name):
    strat_k_fold = StratifiedKFold(n_splits=2, shuffle=True)
    model.fit(X_train, y_train)
    r2                  = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="r2"))
    mean_squared_error  = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="mean_squared_error"))
    mean_absolute_error = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="mean_absolute_error"))
    accuracy            = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="accuracy"))
    balanced_accuracy   = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="balanced_accuracy"))
    precision           = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="precision"))
    recall              = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="recall"))
    f1                  = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="f1"))
    roc_auc             = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="roc_auc"))
    y_pred = model.predict(X_test)
    tn, fp, fn, tp = confusion_matrix(y_pred, y_test).ravel()
    specificity = tn / (tn+fp)

    df_model = pd.DataFrame({"model"            : [name],
                             "r2"               : [r2],
                             "squared_error"    : [mean_squared_error],
                             "absolute_error"   : [mean_absolute_error],
                             "accuracy"         : [accuracy],
                             "balanced_accuracy": [balanced_accuracy],
                             "precision"        : [precision],
                             "recall"           : [recall],
                             "f1"               : [f1],
                             "roc_auc"          : [roc_auc],
                             "specificity"      : [specificity]}) 
    return df_model

In [98]:
models = {"rg": LinearRegression(),
          "logit": LogisticRegression(),
          "knn": KNeighborsClassifier(),
          "gnb": GaussianNB(),
          "bnb": BernoulliNB(),
          "mnb": MultinomialNB(),
          "decisiontree": DecisionTreeClassifier(),
          "randomforest": RandomForestClassifier(),
          "xgboost": GradientBoostingClassifier(),
          "linearsvc": LinearSVC(),
          "svc": SVC(probability=True),
          "MLPC": MLPClassifier()
         }

models_df = pd.concat([baseline_report(model, X_train, X_test, y_train, y_test, name) for (name, model) in models.items()])

ValueError: Supported target types are: ('binary', 'multiclass'). Got 'continuous' instead.

In [99]:
models_df

NameError: name 'models_df' is not defined

#### Iris

In [101]:
X = iris.data
y = iris.target

In [102]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [105]:
def baseline_report(model, X_train, X_test, y_train, y_test, name):
    strat_k_fold = StratifiedKFold(n_splits=2, shuffle=True)
    model.fit(X_train, y_train)
    r2                  = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="r2"))
    mean_squared_error  = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="mean_squared_error"))
    mean_absolute_error = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="mean_absolute_error"))
    accuracy            = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="accuracy"))
    balanced_accuracy   = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="balanced_accuracy"))
    precision           = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="precision"))
    recall              = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="recall"))
    f1                  = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="f1"))
    roc_auc             = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring="roc_auc"))
    y_pred = model.predict(X_test)
    tn, fp, fn, tp = confusion_matrix(y_pred, y_test).ravel()
    specificity = tn / (tn+fp)

    df_model = pd.DataFrame({"model"            : [name],
                             "r2"               : [r2],
                             "squared_error"    : [mean_squared_error],
                             "absolute_error"   : [mean_absolute_error],
                             "accuracy"         : [accuracy],
                             "balanced_accuracy": [balanced_accuracy],
                             "precision"        : [precision],
                             "recall"           : [recall],
                             "f1"               : [f1],
                             "roc_auc"          : [roc_auc],
                             "specificity"      : [specificity]}) 
    return df_model

In [106]:
models = {"rg": LinearRegression(),
          "logit": LogisticRegression(),
          "knn": KNeighborsClassifier(),
          "gnb": GaussianNB(),
          "bnb": BernoulliNB(),
          "mnb": MultinomialNB(),
          "decisiontree": DecisionTreeClassifier(),
          "randomforest": RandomForestClassifier(),
          "xgboost": GradientBoostingClassifier(),
          "linearsvc": LinearSVC(),
          "svc": SVC(probability=True),
          "MLPC": MLPClassifier()
         }

models_df = pd.concat([baseline_report(model, X_train, X_test, y_train, y_test, name) for (name, model) in models.items()])

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

In [ ]:
models_df