# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC, SVC
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_score
from sklearn import preprocessing

## Regression Model Evaluation

Load the boston dataset using sklearn and get the datasets X and y containing the target and the rest of the variables

In [3]:
X, y = load_boston(return_X_y=True)
print(X.shape)

(506, 13)


### Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8)
print(f'X_train: {X_train.shape}')
print(f'y_train shape is: {y_train.shape}')
print(f'X_test shape is: {X_test.shape}')
print(f'y_test shape is: {y_test.shape}')

X_train: (404, 13)
y_train shape is: (404,)
X_test shape is: (102, 13)
y_test shape is: (102,)


### Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [32]:
boston_model = LinearRegression()
res = boston_model.fit(X_train, y_train)
y_train_pred = boston_model.predict(X_train)
y_test_pred  = boston_model.predict(X_test)

### Calculate and print R-squared for both the training and the testing set.

In [29]:
print(f' R-squared train: {r2_score(y_train, y_train_pred)}') 
print(f' R-squared test:  {r2_score(y_test, y_test_pred)}') 

 R-squared train: 0.7344713118301535
 R-squared test:  0.7415084833209453


### Calculate and print mean squared error for both the training and the testing set.

In [36]:
print(f' Mean squared error train: {mean_squared_error(y_train, y_train_pred)}') 
print(f' Mean squared error test: {mean_squared_error(y_test, y_test_pred)}') 

 Mean squared error train: 21.7835673193422
 Mean squared error test: 23.60481820529573


### Calculate and print mean absolute error for both the training and the testing set.

In [37]:
print(f' Mean absolute error train: {mean_absolute_error(y_train, y_train_pred)}') 
print(f' Mean absolute error test: {mean_absolute_error(y_test, y_test_pred)}') 

 Mean absolute error train: 3.2194859581705715
 Mean absolute error test: 3.4903147378744803


## Classification Model Evaluation

Load the iris dataset using sklearn and get the datasets X and y containing the target and the rest of the variables

In [38]:
X, y = load_iris(return_X_y=True)
print(X.shape)

(150, 4)


### Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8)
print(f'X_train: {X_train.shape}')
print(f'y_train shape is: {y_train.shape}')
print(f'X_test shape is: {X_test.shape}')
print(f'y_test shape is: {y_test.shape}')

X_train: (120, 4)
y_train shape is: (120,)
X_test shape is: (30, 4)
y_test shape is: (30,)


### Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [40]:
iris_model = LogisticRegression()
res = iris_model.fit(X_train, y_train)
y_train_pred = iris_model.predict(X_train)
y_test_pred  = iris_model.predict(X_test)

### Calculate and print the accuracy score for both the training and the testing set.

In [44]:
confusion_train= confusion_matrix(y_train, y_train_pred)
accuracy_train = accuracy_score(y_train, y_train_pred)

confusion_test= confusion_matrix(y_test, y_test_pred)
accuracy_test = accuracy_score(y_test, y_test_pred)

print(f'Accuracy score train: {accuracy_train}')
print(f'Accuracy score test: {accuracy_test}')

Accuracy score train: 0.9916666666666667
Accuracy score test: 0.9333333333333333


### Calculate and print the balanced accuracy score for both the training and the testing set.

In [45]:
confusion_train= balanced_accuracy_score(y_train, y_train_pred)
confusion_test= balanced_accuracy_score(y_test, y_test_pred)

print(f'Balanced accuracy score train: {confusion_train}')
print(f'Balanced accuracy score test: {confusion_test}')

Balanced accuracy score train: 0.9912280701754387
Balanced accuracy score test: 0.9444444444444445


### Calculate and print the precision score for both the training and the testing set.

In [49]:
precision_train= precision_score(y_train, y_train_pred, average='macro')
precision_test= precision_score(y_test, y_test_pred, average='macro')

print(f'Precision score train: {precision_train}')
print(f'Precision score test: {precision_test}')

Precision score train: 0.9922480620155039
Precision score test: 0.9333333333333332


### Calculate and print the recall score for both the training and the testing set.

In [50]:
recall_train= recall_score(y_train, y_train_pred, average='macro')
recall_test= recall_score(y_test, y_test_pred, average='macro')

print(f'Recall score train: {recall_train}')
print(f'Recall score test: {recall_test}')

Recall score train: 0.9912280701754387
Recall score test: 0.9444444444444445


### Calculate and print the F1 score for both the training and the testing set.

In [51]:
f1_train= f1_score(y_train, y_train_pred, average='macro')
f1_test= f1_score(y_test, y_test_pred, average='macro')

print(f'F1 score train: {f1_train}')
print(f'F1 score test: {f1_test}')

F1 score train: 0.9916339869281044
F1 score test: 0.9326599326599326


### Generate confusion matrices for both the training and the testing set.

In [53]:
# train
confusion_train= confusion_matrix(y_train, y_train_pred)
print(f'Confusion matrix train: \n{confusion_train}')

Confusion matrix: 
[[40  0  0]
 [ 0 37  1]
 [ 0  0 42]]


In [54]:
# test
confusion_test= confusion_matrix(y_test, y_test_pred)
print(f'Confusion matrix _test: \n{confusion_test}')

Confusion matrix _test: 
[[10  0  0]
 [ 0 10  2]
 [ 0  0  8]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [24]:
def baseline_report(model, X_train, X_test, y_train, y_test, name):
    strat_k_fold = StratifiedKFold(n_splits=5, shuffle=True)
    model.fit(X_train, y_train)
    accuracy     = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring='accuracy'))
    precision    = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring='precision', average='macro'))
    recall       = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring='recall', average='macro'))
    f1score      = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring='f1'))
    rocauc       = np.mean(cross_val_score(model, X_train, y_train, cv=strat_k_fold, scoring='roc_auc'))
    y_pred = model.predict(X_test)
    logloss      = log_loss(y_test, y_pred)   # SVC & LinearSVC unable to use cvs

    df_model = pd.DataFrame({'model'        : [name],
                             'accuracy'     : [accuracy],
                             'precision'    : [precision],
                             'recall'       : [recall],
                             'f1score'      : [f1score],
                             'rocauc'       : [rocauc],
                             'logloss'      : [logloss]})   # timetaken: to be used for comparison later
    return df_model

In [25]:
X, y = load_boston(return_X_y=True)
print(X.shape)

X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8)
lab_enc = preprocessing.LabelEncoder()
y_train = lab_enc.fit_transform(y_train)
y_test = lab_enc.fit_transform(y_test)

print(f'X_train: {X_train.shape}')
print(f'y_train shape is: {y_train.shape}')
print(f'X_test shape is: {X_test.shape}')
print(f'y_test shape is: {y_test.shape}')

boston_model = RandomForestClassifier()
res = boston_model.fit(X_train, y_train)
y_train_pred = boston_model.predict(X_train)
y_test_pred  = boston_model.predict(X_test)

print(f' R-squared train: {r2_score(y_train, y_train_pred)}') 
print(f' R-squared test:  {r2_score(y_test, y_test_pred)}') 

print(f' Mean squared error train: {mean_squared_error(y_train, y_train_pred)}') 
print(f' Mean squared error test: {mean_squared_error(y_test, y_test_pred)}') 

print(f' Mean absolute error train: {mean_absolute_error(y_train, y_train_pred)}') 
print(f' Mean absolute error test: {mean_absolute_error(y_test, y_test_pred)}') 

(506, 13)
X_train: (404, 13)
y_train shape is: (404,)
X_test shape is: (102, 13)
y_test shape is: (102,)
 R-squared train: 1.0
 R-squared test:  -6.718019647832363
 Mean squared error train: 0.0
 Mean squared error test: 4482.745098039216
 Mean absolute error train: 0.0
 Mean absolute error test: 56.666666666666664


In [28]:
X, y = load_iris(return_X_y=True)
print(X.shape)
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8)
print(f'X_train: {X_train.shape}')
print(f'y_train shape is: {y_train.shape}')
print(f'X_test shape is: {X_test.shape}')
print(f'y_test shape is: {y_test.shape}')
iris_model = RandomForestClassifier()
res = iris_model.fit(X_train, y_train)
y_train_pred = iris_model.predict(X_train)
y_test_pred  = iris_model.predict(X_test)

accuracy_train = accuracy_score(y_train, y_train_pred)
accuracy_test = accuracy_score(y_test, y_test_pred)
print(f'Accuracy score train: {accuracy_train}')
print(f'Accuracy score test: {accuracy_test}')

confusion_train= balanced_accuracy_score(y_train, y_train_pred)
confusion_test= balanced_accuracy_score(y_test, y_test_pred)
print(f'Balanced accuracy score train: {confusion_train}')
print(f'Balanced accuracy score test: {confusion_test}')

precision_train= precision_score(y_train, y_train_pred, average='macro')
precision_test= precision_score(y_test, y_test_pred, average='macro')
print(f'Precision score train: {precision_train}')
print(f'Precision score test: {precision_test}')

recall_train= recall_score(y_train, y_train_pred, average='macro')
recall_test= recall_score(y_test, y_test_pred, average='macro')
print(f'Recall score train: {recall_train}')
print(f'Recall score test: {recall_test}')

f1_train= f1_score(y_train, y_train_pred, average='macro')
f1_test= f1_score(y_test, y_test_pred, average='macro')
print(f'F1 score train: {f1_train}')
print(f'F1 score test: {f1_test}')

confusion_train= confusion_matrix(y_train, y_train_pred)
print(f'Confusion matrix train: \n{confusion_train}')
confusion_test= confusion_matrix(y_test, y_test_pred)
print(f'Confusion matrix _test: \n{confusion_test}')

(150, 4)
X_train: (120, 4)
y_train shape is: (120,)
X_test shape is: (30, 4)
y_test shape is: (30,)
Accuracy score train: 1.0
Accuracy score test: 0.9333333333333333
Balanced accuracy score train: 1.0
Balanced accuracy score test: 0.9296296296296296
Precision score train: 1.0
Precision score test: 0.9296296296296296
Recall score train: 1.0
Recall score test: 0.9296296296296296
F1 score train: 1.0
F1 score test: 0.9296296296296296
Confusion matrix train: 
[[39  0  0]
 [ 0 41  0]
 [ 0  0 40]]
Confusion matrix _test: 
[[11  0  0]
 [ 0  8  1]
 [ 0  1  9]]
