# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import numpy as np

## Regression Model Evaluation

Load the boston dataset using sklearn and get the datasets X and y containing the target and the rest of the variables

In [2]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

### Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [3]:
boston_full = pd.DataFrame(data=boston.data, columns=boston.feature_names)
boston_full['MEDV'] = boston.target

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

### Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [5]:
from sklearn.linear_model import LinearRegression

LinReg = LinearRegression().fit(X_train, y_train)

y_test_pred = LinReg.predict(X_test)

y_train_pred = LinReg.predict(X_train)


### Calculate and print R-squared for both the training and the testing set.

In [6]:
from sklearn.metrics import r2_score
y_test_pred_r2 = r2_score(y_test, y_test_pred)
y_train_pred_r2 = r2_score(y_train, y_train_pred)

print(f'R2 Train: {y_train_pred_r2:.3f}\nR2 Test: {y_test_pred_r2:.3f}')

R2 Train: 0.762
R2 Test: 0.530


### Calculate and print mean squared error for both the training and the testing set.

In [7]:
print(f'R2 Train: {np.mean(y_train_pred_r2)}\nR2 Test: {np.mean(y_test_pred_r2)}')

R2 Train: 0.7624075606911873
R2 Test: 0.5300888977311797


## Classification Model Evaluation

Load the iris dataset using sklearn and get the datasets X and y containing the target and the rest of the variables

In [8]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

### Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state = 42)

### Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [10]:
from sklearn.linear_model import LogisticRegression
LogR = LogisticRegression(random_state=0).fit(X, y)

y_test_pred = LogR.predict(X_test)
y_train_pred = LogR.predict(X_train)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


### Calculate and print the accuracy score for both the training and the testing set.

In [11]:
from sklearn.metrics\
import accuracy_score, balanced_accuracy_score, precision_score, recall_score, f1_score,confusion_matrix

In [12]:
print(f'Train accuracy: {accuracy_score(y_train, y_train_pred, normalize=False)}\n'
      f'Test accuracy: {accuracy_score(y_test, y_test_pred, normalize=False)}')

Train accuracy: 116
Test accuracy: 30


### Calculate and print the balanced accuracy score for both the training and the testing set.

In [13]:
print(f'Train balanced accuracy: {balanced_accuracy_score(y_train, y_train_pred):.4f}\n'
      f'Test balanced accuracy: {balanced_accuracy_score(y_test, y_test_pred):.4f}')

Train balanced accuracy: 0.9671
Test balanced accuracy: 1.0000


### Calculate and print the precision score for both the training and the testing set.

In [14]:
print(f'Train precision: {precision_score(y_train, y_train_pred, average="weighted"):.4f}\n'
      f'Test precision: {precision_score(y_test, y_test_pred, average="weighted"):.4f}')

Train precision: 0.9675
Test precision: 1.0000


### Calculate and print the recall score for both the training and the testing set.

In [15]:
print(f'Train recall: {recall_score(y_train, y_train_pred, average="weighted"):.4f}\n'
      f'Test recall: {recall_score(y_test, y_test_pred, average="weighted"):.4f}')

Train recall: 0.9667
Test recall: 1.0000


### Calculate and print the F1 score for both the training and the testing set.

In [16]:
print(f'Train F1: {f1_score(y_train, y_train_pred, average="weighted"):.4f}\n'
      f'Test F1: {f1_score(y_test, y_test_pred, average="weighted"):.4f}')

Train F1: 0.9667
Test F1: 1.0000


### Generate confusion matrices for both the training and the testing set.

In [17]:
# train
confusion_matrix(y_train, y_train_pred)

array([[40,  0,  0],
       [ 0, 38,  3],
       [ 0,  1, 38]])

In [18]:
# test
print(f'Test Confusion Matrix\n{confusion_matrix(y_test, y_test_pred)}')

Test Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.