# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import numpy as np

## Regression Model Evaluation

Load the boston dataset using sklearn and get the datasets X and y containing the target and the rest of the variables

In [2]:
from sklearn.datasets import load_boston
boston = load_boston()
boston['data'].shape

(506, 13)

In [3]:
boston['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [4]:
boston['target']

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

### Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [5]:
from sklearn.model_selection import train_test_split

X = pd.DataFrame(boston['data'])
y = pd.DataFrame(boston['target'])

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

### Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [6]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso

In [15]:
lr = LinearRegression().fit(X_train, y_train)
y_pred_train = lr.predict(X_train)
y_pred_test = lr.predict(X_test)

In [13]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(404, 13) (102, 13) (404, 1) (102, 1)


### Calculate and print R-squared for both the training and the testing set.

In [17]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

print(f'The R2 for train set is: {round(r2_score(y_pred_train, y_train),3)}')
print(f'The R2 for test set is: {round(r2_score(y_pred_test, y_test),3)}')

The R2 for train set is: 0.668
The R2 for test set is: 0.633


### Calculate and print mean squared error for both the training and the testing set.

In [19]:
print(f'The Mean Square Error for train set is: {round(mean_squared_error(y_pred_train, y_train),3)}')
print(f'The Mean Square Error for test set is: {round(mean_squared_error(y_pred_test, y_test),3)}')

The Mean Square Error for train set is: 21.641
The Mean Square Error for test set is: 24.291


### Calculate and print mean absolute error for both the training and the testing set.

In [20]:
print(f'The Mean Absolute Error for train set is: {round(mean_absolute_error(y_pred_train, y_train),3)}')
print(f'The Mean Absolute Square Error for test set is: {round(mean_absolute_error(y_pred_test, y_test),3)}')

The Mean Absolute Error for train set is: 3.315
The Mean Absolute Square Error for test set is: 3.189


### BONUS 

In [22]:
ridge = Ridge().fit(X_train, y_train)
y_pred_train = ridge.predict(X_train)
y_pred_test = ridge.predict(X_test)

print(f'The R2 for train set is: {round(r2_score(y_pred_train, y_train),3)}')
print(f'The R2 for test set is: {round(r2_score(y_pred_test, y_test),3)}')

print(f'The Mean Square Error for train set is: {round(mean_squared_error(y_pred_train, y_train),3)}')
print(f'The Mean Square Error for test set is: {round(mean_squared_error(y_pred_test, y_test),3)}')

print(f'The Mean Absolute Error for train set is: {round(mean_absolute_error(y_pred_train, y_train),3)}')
print(f'The Mean Absolute Square Error for test set is: {round(mean_absolute_error(y_pred_test, y_test),3)}')

The R2 for train set is: 0.661
The R2 for test set is: 0.632
The Mean Square Error for train set is: 21.824
The Mean Square Error for test set is: 24.477
The Mean Absolute Error for train set is: 3.3
The Mean Absolute Square Error for test set is: 3.133


In [23]:
lasso = Lasso().fit(X_train, y_train)
y_pred_train = lasso.predict(X_train)
y_pred_test = lasso.predict(X_test)

print(f'The R2 for train set is: {round(r2_score(y_pred_train, y_train),3)}')
print(f'The R2 for test set is: {round(r2_score(y_pred_test, y_test),3)}')

print(f'The Mean Square Error for train set is: {round(mean_squared_error(y_pred_train, y_train),3)}')
print(f'The Mean Square Error for test set is: {round(mean_squared_error(y_pred_test, y_test),3)}')

print(f'The Mean Absolute Error for train set is: {round(mean_absolute_error(y_pred_train, y_train),3)}')
print(f'The Mean Absolute Square Error for test set is: {round(mean_absolute_error(y_pred_test, y_test),3)}')

The R2 for train set is: 0.495
The R2 for test set is: 0.558
The Mean Square Error for train set is: 26.417
The Mean Square Error for test set is: 24.409
The Mean Absolute Error for train set is: 3.65
The Mean Absolute Square Error for test set is: 3.254


Linear Regression and Ridge perform very similar. Lasso has the worst performance of the three models compared.

## Classification Model Evaluation

Load the iris dataset using sklearn and get the datasets X and y containing the target and the rest of the variables

In [24]:
from sklearn.datasets import load_iris
iris = load_iris()

X = iris['data']
y = iris['target']

### Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import balanced_accuracy_score, classification_report, confusion_matrix

### Calculate and print the accuracy score for both the training and the testing set.

In [57]:
logreg = LogisticRegression(solver='lbfgs', multi_class='auto').fit(X_train, y_train)
y_pred_train = logreg.predict(X_train)
y_pred_test = logreg.predict(X_test)

print(f'The accuracy score for training is: {logreg.score(X_train, y_train)}')
print(f'The accuracy score for test is: {logreg.score(X_test, y_test)}')

The accuracy score for training is: 0.975
The accuracy score for test is: 1.0


C:\Users\unoma\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


### Calculate and print the balanced accuracy score for both the training and the testing set.

In [58]:
print(f'The balanced accuracy score for training is: {balanced_accuracy_score(y_train, y_pred_train)}')
print(f'The balanced accuracy score for test is: {balanced_accuracy_score(y_test, y_pred_test)}')

The balanced accuracy score for training is: 0.975609756097561
The balanced accuracy score for test is: 1.0


### Calculate and print the precision score for both the training and the testing set.

In [66]:
# Classification matrix for training set
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      0.93      0.96        41
           2       0.93      1.00      0.96        39

    accuracy                           0.97       120
   macro avg       0.98      0.98      0.97       120
weighted avg       0.98      0.97      0.97       120



In [68]:
# Classification report for test set
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
# The precision score is 0.98 for training and 1.00 for test

### Calculate and print the recall score for both the training and the testing set.

In [ ]:
# The recall is 0.98 for training and 1.00 for test

### Calculate and print the F1 score for both the training and the testing set.

In [ ]:
# The F1 score is 0.97 for training and 1.00 for test

### Generate confusion matrices for both the training and the testing set.

In [71]:
# train
print(confusion_matrix(y_train, y_pred_train))

[[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]


In [72]:
# test
print(confusion_matrix(y_test, y_pred_test))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


## BONUS 

### KNeighbours

In [81]:
knn = KNeighborsClassifier().fit(X_train, y_train)
y_pred_train = knn.predict(X_train)
y_pred_test = knn.predict(X_test)

print(f'The accuracy score for training is: {round(knn.score(X_train, y_train),3)}')
print(f'The accuracy score for test is: {knn.score(X_test, y_test)}')
print(f'The balanced accuracy score for training is: {round(balanced_accuracy_score(y_train, y_pred_train),3)}')
print(f'The balanced accuracy score for test is: {balanced_accuracy_score(y_test, y_pred_test)}')


The accuracy score for training is: 0.967
The accuracy score for test is: 1.0
The balanced accuracy score for training is: 0.967
The balanced accuracy score for test is: 1.0


In [78]:
# Classification Report for Train in KNeighbours
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.97      0.93      0.95        41
           2       0.93      0.97      0.95        39

    accuracy                           0.97       120
   macro avg       0.97      0.97      0.97       120
weighted avg       0.97      0.97      0.97       120



In [80]:
# Classification Report for Test in KNeighbours
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



### RandomForest

In [83]:
rf = RandomForestClassifier(n_estimators=100).fit(X_train, y_train)
y_pred_train = rf.predict(X_train)
y_pred_test = rf.predict(X_test)

print(f'The accuracy score for training is: {round(rf.score(X_train, y_train),3)}')
print(f'The accuracy score for test is: {rf.score(X_test, y_test)}')
print(f'The balanced accuracy score for training is: {round(balanced_accuracy_score(y_train, y_pred_train),3)}')
print(f'The balanced accuracy score for test is: {balanced_accuracy_score(y_test, y_pred_test)}')

The accuracy score for training is: 1.0
The accuracy score for test is: 1.0
The balanced accuracy score for training is: 1.0
The balanced accuracy score for test is: 1.0


In [84]:
# Classification Report for Train in RandomForest
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      1.00      1.00        41
           2       1.00      1.00      1.00        39

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120



In [85]:
# Classification Report for Test in RandomForest
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



The best model seems to be a RandomForest classifier, although the other two (Logistic Regression and KNeighbours) performed very well for train and test set.

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.